export enum ShipmentStatus {
    CREATED = 'CREATED',
    IN_WAREHOUSE = 'IN_WAREHOUSE',
    IN_TRANSIT = 'IN_TRANSIT',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    DELIVERED = 'DELIVERED',
    RETURNED = 'RETURNED',
    CANCELLED = 'CANCELLED',
}
